- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Box
  - Cog
  - Core
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Packed
  - Reach
  #- Train
  - Saltern2
  - Atlas2
  - Cluster2
