- type: antag
  id: Vampire
  name: roles-antag-vampire-name
  playTimeTracker: AntagVampire
  antagonist: true
  setPreference: false
  objective: roles-antag-vampire-objective
  # guides: [ Vampire ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 1h
