- type: loadout
  id: GlassesSecurityNoir
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobDetective
      time: 10h
  equipment:
    eyes: ClothingEyesGlassesNoir
