# Contains modifications made by Ronstation contributors, therefore this file is subject to MIT sublicensed with AGPL v3.0.
- type: antag
  id: ParadoxClone
  playTimeTracker: AntagParadoxClone # Ronstation - modification.
  color: '#D82000' # Ronstation - modification.
  name: roles-antag-paradox-clone-name
  antagonist: true
  objective: roles-antag-paradox-clone-objective
  setPreference: false

# they need to be able to espace when spawning inside a locked room
# TODO: remove this once we got a better spawning loacation selection
- type: startingGear
  id: ParadoxCloneGear
  inhand:
  - ToolboxMechanicalFilledAllTools
  storage:
    back:
    - ClothingHandsGlovesColorYellow
