# Contains modifications made by Ronstation contributors, therefore this file is subject to MIT sublicensed with AGPL v3.0.
- type: antag
  id: HeadRev
  name: roles-antag-rev-head-name
  playTimeTracker: AntagHeadRev # Ronstation - modification.
  color: '#5E9CFF' # Ronstation - modification.
  antagonist: true
  setPreference: true
  objective: roles-antag-rev-head-objective
  guides: [ Revolutionaries ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 1h

- type: antag
  id: Rev
  name: roles-antag-rev-name
  playTimeTracker: AntagRev # Ronstation - modification.
  color: '#5E9CFF' # Ronstation - modification.
  antagonist: true
  setPreference: false
  objective: roles-antag-rev-objective
  guides: [ Revolutionaries ]

- type: startingGear
  id: HeadRevGear
  storage:
    back:
    - Flash
    - ClothingEyesGlassesSunglasses
