# Contains modifications made by Ronstation contributors, therefore this file is subject to MIT sublicensed with AGPL v3.0.
- type: antag
  id: Survivor
  name: roles-antag-survivor-name
  playTimeTracker: AntagSurvivor # Ronstation - modification.
  antagonist: true
  objective: roles-antag-survivor-objective
  # guides: [  ]

- type: antag
  id: Wizard
  name: roles-antag-wizard-name
  playTimeTracker: AntagWizard # Ronstation - modification.
  color: '#40E0D0' # Ronstation - modification.
  antagonist: true
  setPreference: true
  objective: roles-antag-wizard-objective # TODO: maybe give random objs and stationary ones from AntagObjectives and AntagRandomObjectives
  requirements: # I hate time locked roles but this should be enough time for someone to be acclimated
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  guides: [ Wizard ]

# See wizard_startinggear for wiz start gear options
