# Contains modifications made by Ronstation contributors, therefore this file is subject to MIT sublicensed with AGPL v3.0.
- type: antag
  id: InitialInfected
  name: roles-antag-initial-infected-name
  playTimeTracker: AntagInitialInfected # Ronstation - modification.
  color: '#DDA0DD' # Ronstation - modification.
  antagonist: true
  setPreference: true
  objective: roles-antag-initial-infected-objective
  guides: [ Zombies ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h

- type: antag
  id: Zombie
  name: roles-antag-zombie-name
  playTimeTracker: AntagZombie # Ronstation - modification.
  color: '#DDA0DD' # Ronstation - modification.
  antagonist: true
  setPreference: false
  objective: roles-antag-zombie-objective
  guides: [ Zombies ]
